CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) PRIMARY KEY,
  wechat_openid VARCHAR(128) NOT NULL UNIQUE,
  union_id VARCHAR(128),
  nickname VARCHAR(128),
  avatar_url TEXT,
  phone VARCHAR(32),
  source VARCHAR(64) DEFAULT 'miniapp',
  app_user_id VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL REFERENCES users(id),
  template VARCHAR(32) NOT NULL DEFAULT 'universal',
  title VARCHAR(128) NOT NULL DEFAULT '',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  name VARCHAR(128) NOT NULL,
  name_en VARCHAR(128) NOT NULL DEFAULT '',
  role VARCHAR(255) NOT NULL DEFAULT '',
  bio TEXT NOT NULL DEFAULT '',
  company VARCHAR(255) NOT NULL DEFAULT '',
  business VARCHAR(255) NOT NULL DEFAULT '',
  cooperation VARCHAR(255) NOT NULL DEFAULT '',
  location_country VARCHAR(64) NOT NULL DEFAULT '',
  location_city VARCHAR(64) NOT NULL DEFAULT '',
  wechat VARCHAR(128) NOT NULL DEFAULT '',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  github_url TEXT NOT NULL DEFAULT '',
  twitter_url TEXT NOT NULL DEFAULT '',
  banner_url TEXT NOT NULL DEFAULT '',
  avatar_url TEXT NOT NULL DEFAULT '',
  years VARCHAR(32) NOT NULL DEFAULT '',
  tech_stack TEXT NOT NULL DEFAULT '',
  products_count VARCHAR(32) NOT NULL DEFAULT '',
  users_count VARCHAR(32) NOT NULL DEFAULT '',
  footer_title VARCHAR(128) NOT NULL DEFAULT '',
  footer_desc TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS card_projects (
  id VARCHAR(64) PRIMARY KEY,
  card_id VARCHAR(64) NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  title VARCHAR(128) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  thumbnail_url TEXT NOT NULL DEFAULT '',
  link_url TEXT NOT NULL DEFAULT '',
  github_url TEXT NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS card_project_tags (
  id VARCHAR(64) PRIMARY KEY,
  project_id VARCHAR(64) NOT NULL REFERENCES card_projects(id) ON DELETE CASCADE,
  tag_name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS card_videos (
  id VARCHAR(64) PRIMARY KEY,
  card_id VARCHAR(64) NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  title VARCHAR(128) NOT NULL,
  thumbnail_url TEXT NOT NULL DEFAULT '',
  link_url TEXT NOT NULL DEFAULT '',
  views_text VARCHAR(64) NOT NULL DEFAULT '',
  duration_text VARCHAR(32) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS card_custom_blocks (
  id VARCHAR(64) PRIMARY KEY,
  card_id VARCHAR(64) NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  title VARCHAR(128) NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
  id VARCHAR(64) PRIMARY KEY,
  owner_user_id VARCHAR(64) NOT NULL REFERENCES users(id),
  contact_user_id VARCHAR(64) REFERENCES users(id),
  source_card_id VARCHAR(64) REFERENCES cards(id),
  target_card_id VARCHAR(64) REFERENCES cards(id),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  starred BOOLEAN NOT NULL DEFAULT FALSE,
  has_update BOOLEAN NOT NULL DEFAULT FALSE,
  update_type VARCHAR(32) NOT NULL DEFAULT '',
  update_message TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  latest_interaction_text VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_tags (
  id VARCHAR(64) PRIMARY KEY,
  contact_id VARCHAR(64) NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  tag_name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS visitors (
  id VARCHAR(64) PRIMARY KEY,
  owner_user_id VARCHAR(64) NOT NULL REFERENCES users(id),
  visitor_user_id VARCHAR(64) REFERENCES users(id),
  card_id VARCHAR(64) NOT NULL REFERENCES cards(id),
  source VARCHAR(64) NOT NULL DEFAULT '',
  visit_count INT NOT NULL DEFAULT 1,
  first_visit_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_visit_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exchange_records (
  id VARCHAR(64) PRIMARY KEY,
  requester_user_id VARCHAR(64) NOT NULL REFERENCES users(id),
  target_user_id VARCHAR(64) REFERENCES users(id),
  requester_card_id VARCHAR(64) REFERENCES cards(id),
  target_card_id VARCHAR(64) REFERENCES cards(id),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  channel VARCHAR(64) NOT NULL DEFAULT 'qrcode',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL UNIQUE REFERENCES users(id),
  ai_tone VARCHAR(64) NOT NULL DEFAULT '专业且友好',
  public_dynamics BOOLEAN NOT NULL DEFAULT TRUE,
  privacy_mode VARCHAR(64) NOT NULL DEFAULT '交换后可见',
  blacklist_json TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suggestions (
  id VARCHAR(64) PRIMARY KEY,
  user_id VARCHAR(64) REFERENCES users(id),
  content TEXT NOT NULL,
  contact TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
